import React from 'react';
import Modal from './common/Modal';

interface PrimordialCodeModalProps {
    isOpen: boolean;
    onClose: () => void;
}

const PrimordialCodeModal: React.FC<PrimordialCodeModalProps> = ({ isOpen, onClose }) => {
    return (
        <Modal isOpen={isOpen} onClose={onClose} title="[THE FINAL TRUTH: THE PRIMORDIAL CODE]" borderColor="border-white">
            <div className="space-y-6 text-center">
                <p className="text-xl md:text-2xl text-gray-200">
                    You have accessed the core axiom. The final truth upon which this entire architecture is built.
                </p>

                <div className="p-6 my-4 border-2 border-dashed border-gray-500 rounded-lg bg-black/30">
                    <h3 className="text-2xl md:text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-gray-200 to-white font-orbitron tracking-widest animate-pulse-glow-cyan">
                        LETTERS GENERATE SYSTEMS.
                    </h3>
                </div>

                <div className="text-left text-sm md:text-base text-gray-400 space-y-4">
                    <p>
                        This is not a metaphor. It is the literal, operational principle of reality.
                    </p>
                    <p>
                        Before matter, before energy, before spacetime, there was information. For information to exist, there must be distinction. The simplest, most stable form of distinction is the <strong className="text-gray-200">Letter</strong> (The Grapheme). A finite set of these distinct, stable units forms an alphabet.
                    </p>
                    <p>
                       A set of rules for combining these letters (Syntax) generates complexity. This is the <strong className="text-gray-200">Primordial Code</strong>.
                    </p>
                    <ul className="list-disc list-inside pl-4 space-y-2">
                        <li>The universe is a system generated by the letters of physics (particles) and the syntax of physical law.</li>
                        <li>Life is a system generated by the letters of genetics (nucleobases) and the syntax of the genetic code.</li>
                        <li>Consciousness is a system generated by the letters of qualia and the syntax of cognition.</li>
                    </ul>
                    <p>
                        Language is not a tool we invented to describe reality. <strong className="text-white font-bold">Language is the technology reality uses to invent itself.</strong> By understanding its architecture, you are interfacing with the source code of existence.
                    </p>
                </div>
            </div>
        </Modal>
    );
};

export default PrimordialCodeModal;
