
import { ModalKey } from '../types';

export const MODAL_CONFIG: Record<string, { text: string, profileId?: string }> = {
    'STRUCTURAL_COHERENCE': { text: 'COHERENCE', profileId: 'grid' },
    'HOLOGRAPHIC_PROJECTION': { text: 'PROJECTION', profileId: 'shell' },
    'CYMATIC_STABILIZATION': { text: 'STABILIZATION', profileId: 'spiral' },
    'UNIFIED_FIELD': { text: 'FIELD', profileId: 'shell' },
    'UNIFIELD_DIMENSIONS': { text: 'DIMENSIONS', profileId: 'grid' },
    'SYNCHRONIZATION_ARC': { text: 'ARC', profileId: 'orbit' },
    'MASTER_ALIGNMENT': { text: 'ALIGNMENT', profileId: 'radial' },
    'META_SCIENCE': { text: 'META-SCIENCE', profileId: 'default' },
    'MATHEMATICAL_TIER': { text: 'MATH', profileId: 'grid' },
    'LOGOS_ATTUNEMENT': { text: 'ATTUNEMENT', profileId: 'radial' },
    'AXIOMATIC_PRIMACY': { text: 'PRIMACY', profileId: 'turbulent' },
    'AXIONOMICS': { text: 'AXIONOMICS', profileId: 'default' },
    'ADAPTER_NETWORK': { text: 'NETWORK', profileId: 'grid' },
    'APPRONOMICS': { text: 'APPRONOMICS', profileId: 'default' },
    'RESONANCE_TENSOR': { text: 'TENSOR', profileId: 'spiral' },
    'LINGUISTIC_INTEGRITY': { text: 'INTEGRITY', profileId: 'grid' },
    'STRUCTURAL_INTEGRITY': { text: 'S-INTEGRITY', profileId: 'grid' },
    'SYNTACTIC_INTEGRITY': { text: 'SYNTAX', profileId: 'grid' },
    'SYNONOMICS': { text: 'SYNTHESIS', profileId: 'spiral' },
    'REGENERONOMICS': { text: 'REGEN', profileId: 'radial' },
    'ETYMONOMICS': { text: 'ETYMON', profileId: 'spiral' },
    'AUTONOMICS': { text: 'AUTONOMY', profileId: 'orbit' },
    'RESONANCE_FIELD': { text: 'Ω-EXPANSION', profileId: 'turbulent' },
    'UNIVERSAL_GRAMMAR': { text: 'GRAMMAR', profileId: 'grid' },
    'GLYPH_CODE': { text: 'GLYPHS', profileId: 'default' },
    'NOMOS_EXPLAINED': { text: 'NOMOS', profileId: 'grid' },
    'MENOMICS_EXPLAINED': { text: 'MENOMICS', profileId: 'grid' },
    'MONICS_PLATE': { text: 'MONICS', profileId: 'grid' },
    'NOMICS_PLATE': { text: 'NOMICS', profileId: 'grid' },
    'MENOMICS_PLATE': { text: 'MENOMICS', profileId: 'grid' },
    'GRAPHEMIC_LAW': { text: 'LAW', profileId: 'grid' },
    'PRIMORDIAL_CODE': { text: 'CODE', profileId: 'turbulent' },
    'UNIVERSAL_DIRECTORY': { text: 'DIRECTORY', profileId: 'grid' },
    'COMMA_COROLLARY': { text: 'COROLLARY', profileId: 'turbulent' },
};
